# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/stuart/Source/qgis_redistricting/ui/DistrictDataTable.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_qdwDistrictData(object):
    def setupUi(self, qdwDistrictData):
        qdwDistrictData.setObjectName("qdwDistrictData")
        qdwDistrictData.resize(538, 296)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.dockWidgetContents)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lblPlanName = QtWidgets.QLabel(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblPlanName.setFont(font)
        self.lblPlanName.setObjectName("lblPlanName")
        self.horizontalLayout.addWidget(self.lblPlanName)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.frame = QtWidgets.QFrame(self.dockWidgetContents)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnCopy = QtWidgets.QToolButton(self.frame)
        self.btnCopy.setAutoRaise(True)
        self.btnCopy.setObjectName("btnCopy")
        self.horizontalLayout_2.addWidget(self.btnCopy)
        self.btnRecalculate = QtWidgets.QToolButton(self.frame)
        self.btnRecalculate.setAutoRaise(True)
        self.btnRecalculate.setObjectName("btnRecalculate")
        self.horizontalLayout_2.addWidget(self.btnRecalculate)
        self.btnAddFields = QtWidgets.QToolButton(self.frame)
        self.btnAddFields.setAutoRaise(True)
        self.btnAddFields.setObjectName("btnAddFields")
        self.horizontalLayout_2.addWidget(self.btnAddFields)
        self.btnHelp = QtWidgets.QToolButton(self.frame)
        self.btnHelp.setAutoRaise(True)
        self.btnHelp.setObjectName("btnHelp")
        self.horizontalLayout_2.addWidget(self.btnHelp)
        self.horizontalLayout.addWidget(self.frame)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.splitter = QtWidgets.QSplitter(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.gbxDistrictDemographics = QtWidgets.QGroupBox(self.splitter)
        self.gbxDistrictDemographics.setObjectName("gbxDistrictDemographics")
        self.gloDistrictDemographics = QtWidgets.QGridLayout(self.gbxDistrictDemographics)
        self.gloDistrictDemographics.setContentsMargins(0, 0, 0, 0)
        self.gloDistrictDemographics.setObjectName("gloDistrictDemographics")
        self.tblDataTable = RdsTableView(self.gbxDistrictDemographics)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblDataTable.sizePolicy().hasHeightForWidth())
        self.tblDataTable.setSizePolicy(sizePolicy)
        self.tblDataTable.setMinimumSize(QtCore.QSize(20, 0))
        self.tblDataTable.setObjectName("tblDataTable")
        self.gloDistrictDemographics.addWidget(self.tblDataTable, 0, 0, 1, 1)
        self.gbxPlanMetrics = QtWidgets.QGroupBox(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbxPlanMetrics.sizePolicy().hasHeightForWidth())
        self.gbxPlanMetrics.setSizePolicy(sizePolicy)
        self.gbxPlanMetrics.setObjectName("gbxPlanMetrics")
        self.gloMetrics = QtWidgets.QGridLayout(self.gbxPlanMetrics)
        self.gloMetrics.setContentsMargins(0, 0, 0, 0)
        self.gloMetrics.setObjectName("gloMetrics")
        self.tblPlanMetrics = QtWidgets.QTableView(self.gbxPlanMetrics)
        self.tblPlanMetrics.setStyleSheet("QHeaderView {\n"
"                                                                        border: none;\n"
"                                                                        padding-left: 5px\n"
"                                                                        }\n"
"                                                                        QHeaderView::section {\n"
"                                                                        border: none;\n"
"                                                                        }")
        self.tblPlanMetrics.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tblPlanMetrics.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tblPlanMetrics.setShowGrid(False)
        self.tblPlanMetrics.setGridStyle(QtCore.Qt.NoPen)
        self.tblPlanMetrics.setObjectName("tblPlanMetrics")
        self.tblPlanMetrics.horizontalHeader().setVisible(False)
        self.tblPlanMetrics.verticalHeader().setDefaultSectionSize(24)
        self.gloMetrics.addWidget(self.tblPlanMetrics, 5, 0, 1, 1)
        self.verticalLayout.addWidget(self.splitter)
        qdwDistrictData.setWidget(self.dockWidgetContents)

        self.retranslateUi(qdwDistrictData)
        QtCore.QMetaObject.connectSlotsByName(qdwDistrictData)

    def retranslateUi(self, qdwDistrictData):
        _translate = QtCore.QCoreApplication.translate
        qdwDistrictData.setWindowTitle(_translate("qdwDistrictData", "QGIS Redistricting - Plan Analysis"))
        self.label.setText(_translate("qdwDistrictData", "Redistricting Plan"))
        self.lblPlanName.setText(_translate("qdwDistrictData", "No plan selected"))
        self.btnCopy.setToolTip(_translate("qdwDistrictData", "Copy entire table to\n"
"                                                                              clipboard"))
        self.btnCopy.setText(_translate("qdwDistrictData", "..."))
        self.btnRecalculate.setToolTip(_translate("qdwDistrictData", "Recalculate"))
        self.btnRecalculate.setStatusTip(_translate("qdwDistrictData", "Reaggregate all\n"
"                                                                              demographics"))
        self.btnRecalculate.setText(_translate("qdwDistrictData", "..."))
        self.btnAddFields.setToolTip(_translate("qdwDistrictData", "Add or edit data\n"
"                                                                              fields"))
        self.btnAddFields.setText(_translate("qdwDistrictData", "..."))
        self.btnHelp.setText(_translate("qdwDistrictData", "..."))
        self.gbxDistrictDemographics.setTitle(_translate("qdwDistrictData", "District Demographics"))
        self.gbxPlanMetrics.setTitle(_translate("qdwDistrictData", "Plan Metrics"))
from .RedistrictingWidgets import RdsTableView
