
# Form implementation generated from reading ui file '/Users/stuart/Source/qgis_redistricting/ui/DistrictDataTable.ui'
#
# Created by: qgis.PyQt UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.gui import QgsDockWidget
from qgis.PyQt import (
    QtCore,
    QtGui,
    QtWidgets
)

from .RedistrictingWidgets import RdsTableView


class Ui_qdwDistrictData(object):
    def setupUi(self, qdwDistrictData):
        qdwDistrictData.setObjectName("qdwDistrictData")
        qdwDistrictData.resize(538, 296)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.dockWidgetContents)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lblPlanName = QtWidgets.QLabel(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblPlanName.setFont(font)
        self.lblPlanName.setObjectName("lblPlanName")
        self.horizontalLayout.addWidget(self.lblPlanName)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                           QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.frame = QtWidgets.QFrame(self.dockWidgetContents)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnDemographics = QtWidgets.QToolButton(self.frame)
        self.btnDemographics.setCheckable(True)
        self.btnDemographics.setChecked(True)
        self.btnDemographics.setAutoRaise(True)
        self.btnDemographics.setObjectName("btnDemographics")
        self.horizontalLayout_2.addWidget(self.btnDemographics)
        self.btnMetrics = QtWidgets.QToolButton(self.frame)
        self.btnMetrics.setCheckable(True)
        self.btnMetrics.setChecked(True)
        self.btnMetrics.setAutoRaise(True)
        self.btnMetrics.setObjectName("btnMetrics")
        self.horizontalLayout_2.addWidget(self.btnMetrics)
        self.btnCopy = QtWidgets.QToolButton(self.frame)
        self.btnCopy.setAutoRaise(True)
        self.btnCopy.setObjectName("btnCopy")
        self.horizontalLayout_2.addWidget(self.btnCopy)
        self.btnRecalculate = QtWidgets.QToolButton(self.frame)
        self.btnRecalculate.setAutoRaise(True)
        self.btnRecalculate.setObjectName("btnRecalculate")
        self.horizontalLayout_2.addWidget(self.btnRecalculate)
        self.btnAddFields = QtWidgets.QToolButton(self.frame)
        self.btnAddFields.setAutoRaise(True)
        self.btnAddFields.setObjectName("btnAddFields")
        self.horizontalLayout_2.addWidget(self.btnAddFields)
        self.btnHelp = QtWidgets.QToolButton(self.frame)
        self.btnHelp.setAutoRaise(True)
        self.btnHelp.setObjectName("btnHelp")
        self.horizontalLayout_2.addWidget(self.btnHelp)
        self.horizontalLayout.addWidget(self.frame)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tblDataTable = RdsTableView(self.dockWidgetContents)
        self.tblDataTable.setMinimumSize(QtCore.QSize(20, 0))
        self.tblDataTable.setSortingEnabled(True)
        self.tblDataTable.setObjectName("tblDataTable")
        self.verticalLayout.addWidget(self.tblDataTable)
        qdwDistrictData.setWidget(self.dockWidgetContents)

        self.retranslateUi(qdwDistrictData)
        QtCore.QMetaObject.connectSlotsByName(qdwDistrictData)
        qdwDistrictData.setTabOrder(self.btnDemographics, self.btnMetrics)
        qdwDistrictData.setTabOrder(self.btnMetrics, self.btnCopy)
        qdwDistrictData.setTabOrder(self.btnCopy, self.btnRecalculate)
        qdwDistrictData.setTabOrder(self.btnRecalculate, self.btnAddFields)
        qdwDistrictData.setTabOrder(self.btnAddFields, self.btnHelp)

    def retranslateUi(self, qdwDistrictData):
        _translate = QtCore.QCoreApplication.translate
        qdwDistrictData.setWindowTitle(_translate("qdwDistrictData", "Redistricting - District Analysis"))
        self.label.setText(_translate("qdwDistrictData", "Plan"))
        self.lblPlanName.setText(_translate("qdwDistrictData", "No plan selected"))
        self.btnDemographics.setToolTip(_translate("qdwDistrictData", "Show/hide district demographic data"))
        self.btnDemographics.setText(_translate("qdwDistrictData", "..."))
        self.btnMetrics.setToolTip(_translate("qdwDistrictData", "Show/hide district metrics"))
        self.btnMetrics.setText(_translate("qdwDistrictData", "..."))
        self.btnCopy.setToolTip(_translate("qdwDistrictData", "Copy entire table to clipboard"))
        self.btnCopy.setText(_translate("qdwDistrictData", "..."))
        self.btnRecalculate.setToolTip(_translate("qdwDistrictData", "Recalculate"))
        self.btnRecalculate.setStatusTip(_translate("qdwDistrictData", "Reaggregate all\n"
                                                    "                                                    demographics"))
        self.btnRecalculate.setText(_translate("qdwDistrictData", "..."))
        self.btnAddFields.setToolTip(_translate("qdwDistrictData", "Add or edit data fields"))
        self.btnAddFields.setText(_translate("qdwDistrictData", "..."))
        self.btnHelp.setToolTip(_translate("qdwDistrictData", "Help on district analysis panel"))
        self.btnHelp.setText(_translate("qdwDistrictData", "..."))
