# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/stuart/Source/redistricting/redistricting/ui/DistrictTools.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_qdwDistrictTools(object):
    def setupUi(self, qdwDistrictTools):
        qdwDistrictTools.setObjectName("qdwDistrictTools")
        qdwDistrictTools.resize(549, 243)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(qdwDistrictTools.sizePolicy().hasHeightForWidth())
        qdwDistrictTools.setSizePolicy(sizePolicy)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setContentsMargins(-1, 4, -1, -1)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnAssign = QtWidgets.QToolButton(self.frame)
        self.btnAssign.setAutoRaise(True)
        self.btnAssign.setObjectName("btnAssign")
        self.horizontalLayout_2.addWidget(self.btnAssign)
        self.btnCommitUpdate = QtWidgets.QToolButton(self.frame)
        self.btnCommitUpdate.setAutoRaise(True)
        self.btnCommitUpdate.setObjectName("btnCommitUpdate")
        self.horizontalLayout_2.addWidget(self.btnCommitUpdate)
        self.btnRollbackUpdate = QtWidgets.QToolButton(self.frame)
        self.btnRollbackUpdate.setAutoRaise(True)
        self.btnRollbackUpdate.setObjectName("btnRollbackUpdate")
        self.horizontalLayout_2.addWidget(self.btnRollbackUpdate)
        self.btnUndo = QtWidgets.QToolButton(self.frame)
        self.btnUndo.setAutoRaise(True)
        self.btnUndo.setObjectName("btnUndo")
        self.horizontalLayout_2.addWidget(self.btnUndo)
        self.btnRedo = QtWidgets.QToolButton(self.frame)
        self.btnRedo.setAutoRaise(True)
        self.btnRedo.setObjectName("btnRedo")
        self.horizontalLayout_2.addWidget(self.btnRedo)
        self.btnPreview = QtWidgets.QToolButton(self.frame)
        self.btnPreview.setAutoRaise(True)
        self.btnPreview.setObjectName("btnPreview")
        self.horizontalLayout_2.addWidget(self.btnPreview)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addWidget(self.frame)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lblTarget = QtWidgets.QLabel(self.dockWidgetContents)
        self.lblTarget.setObjectName("lblTarget")
        self.gridLayout.addWidget(self.lblTarget, 1, 0, 1, 1)
        self.cmbTarget = QtWidgets.QComboBox(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbTarget.sizePolicy().hasHeightForWidth())
        self.cmbTarget.setSizePolicy(sizePolicy)
        self.cmbTarget.setObjectName("cmbTarget")
        self.cmbTarget.addItem("")
        self.cmbTarget.addItem("")
        self.gridLayout.addWidget(self.cmbTarget, 1, 1, 1, 2)
        self.cmbSource = QtWidgets.QComboBox(self.dockWidgetContents)
        self.cmbSource.setObjectName("cmbSource")
        self.cmbSource.addItem("")
        self.cmbSource.addItem("")
        self.gridLayout.addWidget(self.cmbSource, 2, 1, 1, 2)
        self.btnEditPlan = QtWidgets.QToolButton(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnEditPlan.sizePolicy().hasHeightForWidth())
        self.btnEditPlan.setSizePolicy(sizePolicy)
        self.btnEditPlan.setMinimumSize(QtCore.QSize(90, 0))
        self.btnEditPlan.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.btnEditPlan.setObjectName("btnEditPlan")
        self.gridLayout.addWidget(self.btnEditPlan, 0, 2, 1, 1)
        self.lblSource = QtWidgets.QLabel(self.dockWidgetContents)
        self.lblSource.setObjectName("lblSource")
        self.gridLayout.addWidget(self.lblSource, 2, 0, 1, 1)
        self.lblGeoSelect = QtWidgets.QLabel(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblGeoSelect.sizePolicy().hasHeightForWidth())
        self.lblGeoSelect.setSizePolicy(sizePolicy)
        self.lblGeoSelect.setMinimumSize(QtCore.QSize(120, 0))
        self.lblGeoSelect.setWordWrap(False)
        self.lblGeoSelect.setObjectName("lblGeoSelect")
        self.gridLayout.addWidget(self.lblGeoSelect, 3, 0, 1, 1)
        self.lblPlanName = QtWidgets.QLabel(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPlanName.sizePolicy().hasHeightForWidth())
        self.lblPlanName.setSizePolicy(sizePolicy)
        self.lblPlanName.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblPlanName.setFont(font)
        self.lblPlanName.setObjectName("lblPlanName")
        self.gridLayout.addWidget(self.lblPlanName, 0, 1, 1, 1)
        self.lblPlan = QtWidgets.QLabel(self.dockWidgetContents)
        self.lblPlan.setObjectName("lblPlan")
        self.gridLayout.addWidget(self.lblPlan, 0, 0, 1, 1)
        self.cmbGeoSelect = QtWidgets.QComboBox(self.dockWidgetContents)
        self.cmbGeoSelect.setObjectName("cmbGeoSelect")
        self.gridLayout.addWidget(self.cmbGeoSelect, 3, 1, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        qdwDistrictTools.setWidget(self.dockWidgetContents)

        self.retranslateUi(qdwDistrictTools)
        QtCore.QMetaObject.connectSlotsByName(qdwDistrictTools)

    def retranslateUi(self, qdwDistrictTools):
        _translate = QtCore.QCoreApplication.translate
        qdwDistrictTools.setWindowTitle(_translate("qdwDistrictTools", "QGIS Redistricting - Paint Districts"))
        self.btnAssign.setText(_translate("qdwDistrictTools", "..."))
        self.btnCommitUpdate.setText(_translate("qdwDistrictTools", "..."))
        self.btnRollbackUpdate.setText(_translate("qdwDistrictTools", "..."))
        self.btnUndo.setText(_translate("qdwDistrictTools", "..."))
        self.btnRedo.setText(_translate("qdwDistrictTools", "..."))
        self.btnPreview.setText(_translate("qdwDistrictTools", "..."))
        self.lblTarget.setText(_translate("qdwDistrictTools", "Target"))
        self.cmbTarget.setItemText(0, _translate("qdwDistrictTools", "Unassigned"))
        self.cmbTarget.setItemText(1, _translate("qdwDistrictTools", "New district"))
        self.cmbSource.setItemText(0, _translate("qdwDistrictTools", "All"))
        self.cmbSource.setItemText(1, _translate("qdwDistrictTools", "Unassigned"))
        self.btnEditPlan.setToolTip(_translate("qdwDistrictTools", "Change active plan"))
        self.btnEditPlan.setText(_translate("qdwDistrictTools", "Edit Plan"))
        self.lblSource.setText(_translate("qdwDistrictTools", "Source"))
        self.lblGeoSelect.setToolTip(_translate("qdwDistrictTools", "District by geography"))
        self.lblGeoSelect.setStatusTip(_translate("qdwDistrictTools", "When painting districts, all features within the geography specified by the selected field will be painted"))
        self.lblGeoSelect.setText(_translate("qdwDistrictTools", "Geography"))
        self.lblPlanName.setText(_translate("qdwDistrictTools", "No plan selected"))
        self.lblPlan.setText(_translate("qdwDistrictTools", "Redistricting Plan"))
