# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/stuart/Source/qgis_redistricting/ui/DlgCopyPlan.ui'
#
# Created by: qgis.PyQt UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import (
    QtCore,
    QtGui,
    QtWidgets
)

from .RedistrictingWidgets import RdsFileWidget


class Ui_dlgCopyPlan(object):
    def setupUi(self, dlgCopyPlan):
        dlgCopyPlan.setObjectName("dlgCopyPlan")
        dlgCopyPlan.resize(491, 242)
        self.gridLayout = QtWidgets.QGridLayout(dlgCopyPlan)
        self.gridLayout.setObjectName("gridLayout")
        self.cbxCopyAssignments = QtWidgets.QCheckBox(dlgCopyPlan)
        self.cbxCopyAssignments.setChecked(True)
        self.cbxCopyAssignments.setObjectName("cbxCopyAssignments")
        self.gridLayout.addWidget(self.cbxCopyAssignments, 4, 0, 1, 3)
        self.lblPlanName = QtWidgets.QLabel(dlgCopyPlan)
        self.lblPlanName.setObjectName("lblPlanName")
        self.gridLayout.addWidget(self.lblPlanName, 1, 0, 1, 1)
        self.lblSourcePlan = QtWidgets.QLabel(dlgCopyPlan)
        self.lblSourcePlan.setObjectName("lblSourcePlan")
        self.gridLayout.addWidget(self.lblSourcePlan, 0, 0, 1, 3)
        self.inpPlanName = QtWidgets.QLineEdit(dlgCopyPlan)
        self.inpPlanName.setObjectName("inpPlanName")
        self.gridLayout.addWidget(self.inpPlanName, 1, 1, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                           QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 3)
        self.buttonBox = QtWidgets.QDialogButtonBox(dlgCopyPlan)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel |
                                          QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 6, 2, 1, 1)
        self.lblGeoPackage = QtWidgets.QLabel(dlgCopyPlan)
        self.lblGeoPackage.setObjectName("lblGeoPackage")
        self.gridLayout.addWidget(self.lblGeoPackage, 3, 0, 1, 1)
        self.fwGeoPackage = RdsFileWidget(dlgCopyPlan)
        self.fwGeoPackage.setFilter("*.gpkg")
        self.fwGeoPackage.setObjectName("fwGeoPackage")
        self.gridLayout.addWidget(self.fwGeoPackage, 3, 1, 1, 2)
        self.lblDescription = QtWidgets.QLabel(dlgCopyPlan)
        self.lblDescription.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.lblDescription.setObjectName("lblDescription")
        self.gridLayout.addWidget(self.lblDescription, 2, 0, 1, 1)
        self.txtDescription = QtWidgets.QPlainTextEdit(dlgCopyPlan)
        self.txtDescription.setObjectName("txtDescription")
        self.gridLayout.addWidget(self.txtDescription, 2, 1, 1, 2)
        self.lblGeoPackage.setBuddy(self.fwGeoPackage)

        self.retranslateUi(dlgCopyPlan)
        self.buttonBox.accepted.connect(dlgCopyPlan.accept)  # type: ignore
        self.buttonBox.rejected.connect(dlgCopyPlan.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dlgCopyPlan)

    def retranslateUi(self, dlgCopyPlan):
        _translate = QtCore.QCoreApplication.translate
        dlgCopyPlan.setWindowTitle(_translate("dlgCopyPlan", "Copy Redistricting Plan"))
        self.cbxCopyAssignments.setText(_translate("dlgCopyPlan", "Copy assignments"))
        self.lblPlanName.setText(_translate("dlgCopyPlan", "New Plan Name"))
        self.lblSourcePlan.setText(_translate("dlgCopyPlan", "Copy Plan from"))
        self.lblGeoPackage.setText(_translate("dlgCopyPlan", "GeoPackage Path"))
        self.lblDescription.setText(_translate("dlgCopyPlan", "Description"))
