
# Form implementation generated from reading ui file '/Users/stuart/Source/qgis_redistricting/ui/DlgSelectPlan.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import (
    QtCore,
    QtGui,
    QtWidgets
)


class Ui_dlgSelectPlan(object):
    def setupUi(self, dlgSelectPlan):
        dlgSelectPlan.setObjectName("dlgSelectPlan")
        dlgSelectPlan.resize(435, 381)
        self.verticalLayout = QtWidgets.QVBoxLayout(dlgSelectPlan)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lvwPlans = QtWidgets.QTableView(dlgSelectPlan)
        self.lvwPlans.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.lvwPlans.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.lvwPlans.setShowGrid(False)
        self.lvwPlans.setWordWrap(False)
        self.lvwPlans.setObjectName("lvwPlans")
        self.lvwPlans.horizontalHeader().setStretchLastSection(True)
        self.lvwPlans.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.lvwPlans)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btnEdit = QtWidgets.QPushButton(dlgSelectPlan)
        self.btnEdit.setObjectName("btnEdit")
        self.gridLayout.addWidget(self.btnEdit, 2, 3, 1, 1)
        self.btnClose = QtWidgets.QPushButton(dlgSelectPlan)
        self.btnClose.setObjectName("btnClose")
        self.gridLayout.addWidget(self.btnClose, 2, 5, 1, 1)
        self.btnSelect = QtWidgets.QPushButton(dlgSelectPlan)
        self.btnSelect.setEnabled(False)
        self.btnSelect.setDefault(True)
        self.btnSelect.setObjectName("btnSelect")
        self.gridLayout.addWidget(self.btnSelect, 2, 0, 1, 1)
        self.btnDelete = QtWidgets.QPushButton(dlgSelectPlan)
        self.btnDelete.setObjectName("btnDelete")
        self.gridLayout.addWidget(self.btnDelete, 2, 4, 1, 1)
        self.btnNew = QtWidgets.QPushButton(dlgSelectPlan)
        self.btnNew.setObjectName("btnNew")
        self.gridLayout.addWidget(self.btnNew, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(dlgSelectPlan)
        QtCore.QMetaObject.connectSlotsByName(dlgSelectPlan)

    def retranslateUi(self, dlgSelectPlan):
        _translate = QtCore.QCoreApplication.translate
        dlgSelectPlan.setWindowTitle(_translate("dlgSelectPlan", "Select Redistricting Plan"))
        self.btnEdit.setText(_translate("dlgSelectPlan", "Edit"))
        self.btnClose.setText(_translate("dlgSelectPlan", "Close"))
        self.btnSelect.setText(_translate("dlgSelectPlan", "Select"))
        self.btnDelete.setText(_translate("dlgSelectPlan", "Delete"))
        self.btnNew.setText(_translate("dlgSelectPlan", "New "))
