# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/stuart/Source/qgis_redistricting/ui/DlgSplits.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgSplits(object):
    def setupUi(self, dlgSplits):
        dlgSplits.setObjectName("dlgSplits")
        dlgSplits.resize(400, 299)
        dlgSplits.setSizeGripEnabled(True)
        self.gridLayout = QtWidgets.QGridLayout(dlgSplits)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tvSplits = QtWidgets.QTreeView(dlgSplits)
        self.tvSplits.setObjectName("tvSplits")
        self.verticalLayout.addWidget(self.tvSplits)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(dlgSplits)
        QtCore.QMetaObject.connectSlotsByName(dlgSplits)

    def retranslateUi(self, dlgSplits):
        _translate = QtCore.QCoreApplication.translate
        dlgSplits.setWindowTitle(_translate("dlgSplits", "Splits"))
