# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/stuart/Source/qgis_redistricting/ui/DlgSplits.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgSplits(object):
    def setupUi(self, dlgSplits):
        dlgSplits.setObjectName("dlgSplits")
        dlgSplits.resize(400, 299)
        dlgSplits.setSizeGripEnabled(True)
        self.gridLayout = QtWidgets.QGridLayout(dlgSplits)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.cmbGeography = QtWidgets.QComboBox(dlgSplits)
        self.cmbGeography.setObjectName("cmbGeography")
        self.verticalLayout.addWidget(self.cmbGeography)
        self.tvSplits = QtWidgets.QTreeView(dlgSplits)
        self.tvSplits.setObjectName("tvSplits")
        self.verticalLayout.addWidget(self.tvSplits)
        self.gridLayout.addLayout(self.verticalLayout, 2, 0, 1, 1)
        self.gridLayout2 = QtWidgets.QGridLayout()
        self.gridLayout2.setHorizontalSpacing(15)
        self.gridLayout2.setObjectName("gridLayout2")
        self.lblPlanLabel = QtWidgets.QLabel(dlgSplits)
        self.lblPlanLabel.setObjectName("lblPlanLabel")
        self.gridLayout2.addWidget(self.lblPlanLabel, 0, 0, 1, 1)
        self.lblPlan = QtWidgets.QLabel(dlgSplits)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPlan.sizePolicy().hasHeightForWidth())
        self.lblPlan.setSizePolicy(sizePolicy)
        self.lblPlan.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblPlan.setFont(font)
        self.lblPlan.setObjectName("lblPlan")
        self.gridLayout2.addWidget(self.lblPlan, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout2, 0, 0, 1, 1)

        self.retranslateUi(dlgSplits)
        QtCore.QMetaObject.connectSlotsByName(dlgSplits)

    def retranslateUi(self, dlgSplits):
        _translate = QtCore.QCoreApplication.translate
        dlgSplits.setWindowTitle(_translate("dlgSplits", "Splits"))
        self.lblPlanLabel.setText(_translate("dlgSplits", "Redistricting Plan"))
        self.lblPlan.setText(_translate("dlgSplits", "No plan selected"))
