
# Form implementation generated from reading ui file '/Users/stuart/Source/qgis_redistricting/ui/PendingChanges.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.gui import QgsDockWidget
from qgis.PyQt import (
    QtCore,
    QtGui,
    QtWidgets
)


class Ui_qdwPendingChanges(object):
    def setupUi(self, qdwPendingChanges):
        qdwPendingChanges.setObjectName("qdwPendingChanges")
        qdwPendingChanges.resize(271, 444)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.dockWidgetContents)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                           QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnDemographics = QtWidgets.QToolButton(self.frame)
        self.btnDemographics.setCheckable(True)
        self.btnDemographics.setChecked(True)
        self.btnDemographics.setAutoRaise(True)
        self.btnDemographics.setObjectName("btnDemographics")
        self.horizontalLayout.addWidget(self.btnDemographics)
        self.btnHelp = QtWidgets.QToolButton(self.frame)
        self.btnHelp.setAutoRaise(True)
        self.btnHelp.setObjectName("btnHelp")
        self.horizontalLayout.addWidget(self.btnHelp)
        self.verticalLayout.addWidget(self.frame)
        self.tblPending = QtWidgets.QTableView(self.dockWidgetContents)
        self.tblPending.setStyleSheet("QHeaderView::section {padding-right: 5px;}")
        self.tblPending.setCornerButtonEnabled(False)
        self.tblPending.setObjectName("tblPending")
        self.verticalLayout.addWidget(self.tblPending)
        qdwPendingChanges.setWidget(self.dockWidgetContents)

        self.retranslateUi(qdwPendingChanges)
        QtCore.QMetaObject.connectSlotsByName(qdwPendingChanges)

    def retranslateUi(self, qdwPendingChanges):
        _translate = QtCore.QCoreApplication.translate
        qdwPendingChanges.setWindowTitle(_translate("qdwPendingChanges", "Redistricting - Pending Changes"))
        self.btnDemographics.setToolTip(_translate("qdwPendingChanges", "Toggle demographic data"))
        self.btnDemographics.setText(_translate("qdwPendingChanges", "..."))
        self.btnHelp.setToolTip(_translate("qdwPendingChanges", "Help on pending changes panel"))
        self.btnHelp.setText(_translate("qdwPendingChanges", "..."))
