# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/stuart/Source/qgis_redistricting/ui/PlanMetrics.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_qdwPlanMetrics(object):
    def setupUi(self, qdwPlanMetrics):
        qdwPlanMetrics.setObjectName("qdwPlanMetrics")
        qdwPlanMetrics.resize(400, 300)
        self.vlPlanMetrics = QtWidgets.QWidget()
        self.vlPlanMetrics.setObjectName("vlPlanMetrics")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.vlPlanMetrics)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.vlPlanMetrics)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lblPlanName = QtWidgets.QLabel(self.vlPlanMetrics)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblPlanName.setFont(font)
        self.lblPlanName.setObjectName("lblPlanName")
        self.horizontalLayout.addWidget(self.lblPlanName)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.frame = QtWidgets.QFrame(self.vlPlanMetrics)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnCopy = QtWidgets.QToolButton(self.frame)
        self.btnCopy.setAutoRaise(True)
        self.btnCopy.setObjectName("btnCopy")
        self.horizontalLayout_2.addWidget(self.btnCopy)
        self.btnHelp = QtWidgets.QToolButton(self.frame)
        self.btnHelp.setAutoRaise(True)
        self.btnHelp.setObjectName("btnHelp")
        self.horizontalLayout_2.addWidget(self.btnHelp)
        self.horizontalLayout.addWidget(self.frame)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tblPlanMetrics = QtWidgets.QTableView(self.vlPlanMetrics)
        self.tblPlanMetrics.setStyleSheet("QHeaderView {\n"
"                                                border: none;\n"
"                                                padding-left: 5px\n"
"                                                }\n"
"                                                QHeaderView::section {\n"
"                                                border: none;\n"
"                                                }")
        self.tblPlanMetrics.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tblPlanMetrics.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tblPlanMetrics.setShowGrid(False)
        self.tblPlanMetrics.setGridStyle(QtCore.Qt.NoPen)
        self.tblPlanMetrics.setObjectName("tblPlanMetrics")
        self.tblPlanMetrics.horizontalHeader().setVisible(False)
        self.tblPlanMetrics.horizontalHeader().setStretchLastSection(True)
        self.tblPlanMetrics.verticalHeader().setDefaultSectionSize(24)
        self.verticalLayout.addWidget(self.tblPlanMetrics)
        qdwPlanMetrics.setWidget(self.vlPlanMetrics)

        self.retranslateUi(qdwPlanMetrics)
        QtCore.QMetaObject.connectSlotsByName(qdwPlanMetrics)

    def retranslateUi(self, qdwPlanMetrics):
        _translate = QtCore.QCoreApplication.translate
        qdwPlanMetrics.setWindowTitle(_translate("qdwPlanMetrics", "Redistricting - Plan Analysis"))
        self.label.setText(_translate("qdwPlanMetrics", "Plan"))
        self.lblPlanName.setText(_translate("qdwPlanMetrics", "No plan selected"))
        self.btnCopy.setToolTip(_translate("qdwPlanMetrics", "Copy entire table to clipboard"))
        self.btnCopy.setText(_translate("qdwPlanMetrics", "..."))
        self.btnHelp.setToolTip(_translate("qdwPlanMetrics", "Help on plan analysis panel"))
        self.btnHelp.setText(_translate("qdwPlanMetrics", "..."))
from qgsdockwidget import QgsDockWidget
