# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/stuart/Source/qgis_redistricting/ui/WzpEditPlanPopPage.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wzpPopulation(object):
    def setupUi(self, wzpPopulation):
        wzpPopulation.setObjectName("wzpPopulation")
        wzpPopulation.resize(606, 395)
        self.gridLayout = QtWidgets.QGridLayout(wzpPopulation)
        self.gridLayout.setObjectName("gridLayout")
        self.sbxMaxDeviation = QtWidgets.QDoubleSpinBox(wzpPopulation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbxMaxDeviation.sizePolicy().hasHeightForWidth())
        self.sbxMaxDeviation.setSizePolicy(sizePolicy)
        self.sbxMaxDeviation.setSingleStep(0.1)
        self.sbxMaxDeviation.setObjectName("sbxMaxDeviation")
        self.gridLayout.addWidget(self.sbxMaxDeviation, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 2)
        self.lblPopField = QtWidgets.QLabel(wzpPopulation)
        self.lblPopField.setObjectName("lblPopField")
        self.gridLayout.addWidget(self.lblPopField, 1, 0, 1, 1)
        self.gbxPopLayer = QtWidgets.QGroupBox(wzpPopulation)
        self.gbxPopLayer.setObjectName("gbxPopLayer")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gbxPopLayer)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btnUseGeoLayer = QtWidgets.QRadioButton(self.gbxPopLayer)
        self.btnUseGeoLayer.setChecked(True)
        self.btnUseGeoLayer.setObjectName("btnUseGeoLayer")
        self.gridLayout_2.addWidget(self.btnUseGeoLayer, 0, 0, 1, 3)
        self.btnOtherPopLayer = QtWidgets.QRadioButton(self.gbxPopLayer)
        self.btnOtherPopLayer.setObjectName("btnOtherPopLayer")
        self.gridLayout_2.addWidget(self.btnOtherPopLayer, 1, 0, 1, 3)
        self.lblPopLayer = QtWidgets.QLabel(self.gbxPopLayer)
        self.lblPopLayer.setEnabled(False)
        self.lblPopLayer.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblPopLayer.setIndent(20)
        self.lblPopLayer.setObjectName("lblPopLayer")
        self.gridLayout_2.addWidget(self.lblPopLayer, 2, 0, 1, 1)
        self.cmbPopLayer = RdsMapLayerComboBox(self.gbxPopLayer)
        self.cmbPopLayer.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbPopLayer.sizePolicy().hasHeightForWidth())
        self.cmbPopLayer.setSizePolicy(sizePolicy)
        self.cmbPopLayer.setAllowEmptyLayer(True)
        self.cmbPopLayer.setObjectName("cmbPopLayer")
        self.gridLayout_2.addWidget(self.cmbPopLayer, 2, 1, 1, 1)
        self.cmbJoinField = gui.QgsFieldComboBox(self.gbxPopLayer)
        self.cmbJoinField.setEnabled(False)
        self.cmbJoinField.setObjectName("cmbJoinField")
        self.gridLayout_2.addWidget(self.cmbJoinField, 3, 1, 1, 1)
        self.lblJoinField = QtWidgets.QLabel(self.gbxPopLayer)
        self.lblJoinField.setEnabled(False)
        self.lblJoinField.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblJoinField.setObjectName("lblJoinField")
        self.gridLayout_2.addWidget(self.lblJoinField, 3, 0, 1, 1)
        self.gridLayout.addWidget(self.gbxPopLayer, 0, 0, 1, 2)
        self.lblVAPField = QtWidgets.QLabel(wzpPopulation)
        self.lblVAPField.setObjectName("lblVAPField")
        self.gridLayout.addWidget(self.lblVAPField, 3, 0, 1, 1)
        self.cmbPopField = RdsFieldComboBox(wzpPopulation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbPopField.sizePolicy().hasHeightForWidth())
        self.cmbPopField.setSizePolicy(sizePolicy)
        self.cmbPopField.setObjectName("cmbPopField")
        self.gridLayout.addWidget(self.cmbPopField, 1, 1, 1, 1)
        self.lblMaxDeviation = QtWidgets.QLabel(wzpPopulation)
        self.lblMaxDeviation.setObjectName("lblMaxDeviation")
        self.gridLayout.addWidget(self.lblMaxDeviation, 2, 0, 1, 1)
        self.cmbVAPField = RdsFieldComboBox(wzpPopulation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbVAPField.sizePolicy().hasHeightForWidth())
        self.cmbVAPField.setSizePolicy(sizePolicy)
        self.cmbVAPField.setAllowEmptyFieldName(True)
        self.cmbVAPField.setObjectName("cmbVAPField")
        self.gridLayout.addWidget(self.cmbVAPField, 3, 1, 1, 1)
        self.lblCVAPField = QtWidgets.QLabel(wzpPopulation)
        self.lblCVAPField.setObjectName("lblCVAPField")
        self.gridLayout.addWidget(self.lblCVAPField, 4, 0, 1, 1)
        self.cmbCVAPField = RdsFieldComboBox(wzpPopulation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbCVAPField.sizePolicy().hasHeightForWidth())
        self.cmbCVAPField.setSizePolicy(sizePolicy)
        self.cmbCVAPField.setAllowEmptyFieldName(True)
        self.cmbCVAPField.setObjectName("cmbCVAPField")
        self.gridLayout.addWidget(self.cmbCVAPField, 4, 1, 1, 1)
        self.lblPopLayer.setBuddy(self.cmbPopLayer)
        self.lblJoinField.setBuddy(self.cmbJoinField)

        self.retranslateUi(wzpPopulation)
        self.cmbPopLayer.layerChanged['QgsMapLayer*'].connect(self.cmbPopField.setLayer)
        self.cmbPopLayer.layerChanged['QgsMapLayer*'].connect(self.cmbVAPField.setLayer)
        self.cmbPopLayer.layerChanged['QgsMapLayer*'].connect(self.cmbCVAPField.setLayer)
        self.cmbPopLayer.layerChanged['QgsMapLayer*'].connect(self.cmbJoinField.setLayer)
        self.btnOtherPopLayer.toggled['bool'].connect(self.cmbPopLayer.setEnabled)
        self.btnOtherPopLayer.toggled['bool'].connect(self.cmbJoinField.setEnabled)
        self.btnOtherPopLayer.toggled['bool'].connect(self.lblJoinField.setEnabled)
        self.btnOtherPopLayer.toggled['bool'].connect(self.lblPopLayer.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(wzpPopulation)
        wzpPopulation.setTabOrder(self.btnUseGeoLayer, self.btnOtherPopLayer)
        wzpPopulation.setTabOrder(self.btnOtherPopLayer, self.cmbPopField)
        wzpPopulation.setTabOrder(self.cmbPopField, self.sbxMaxDeviation)
        wzpPopulation.setTabOrder(self.sbxMaxDeviation, self.cmbVAPField)

    def retranslateUi(self, wzpPopulation):
        _translate = QtCore.QCoreApplication.translate
        wzpPopulation.setWindowTitle(_translate("wzpPopulation", "Population"))
        wzpPopulation.setTitle(_translate("wzpPopulation", "Population"))
        wzpPopulation.setSubTitle(_translate("wzpPopulation", "Configure population data source"))
        self.sbxMaxDeviation.setPrefix(_translate("wzpPopulation", "±"))
        self.sbxMaxDeviation.setSuffix(_translate("wzpPopulation", "%"))
        self.lblPopField.setText(_translate("wzpPopulation", "Total Population Field"))
        self.gbxPopLayer.setTitle(_translate("wzpPopulation", "Population Layer"))
        self.btnUseGeoLayer.setText(_translate("wzpPopulation", "Use the geography layer"))
        self.btnOtherPopLayer.setText(_translate("wzpPopulation", "Use a separate population layer"))
        self.lblPopLayer.setText(_translate("wzpPopulation", "Layer"))
        self.lblJoinField.setText(_translate("wzpPopulation", "Join Field"))
        self.lblVAPField.setText(_translate("wzpPopulation", "Voting Age Population Field"))
        self.lblMaxDeviation.setText(_translate("wzpPopulation", "Maximum Deviation"))
        self.lblCVAPField.setText(_translate("wzpPopulation", "Citizen VAP Field"))
from qgis import gui
from .RedistrictingWidgets import RdsFieldComboBox, RdsMapLayerComboBox
