# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/stuart/Source/qgis_redistricting/ui/WzpEditPlanImportPage.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wzpImport(object):
    def setupUi(self, wzpImport):
        wzpImport.setObjectName("wzpImport")
        wzpImport.resize(544, 467)
        self.gridLayout_2 = QtWidgets.QGridLayout(wzpImport)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lblGeoCol = QtWidgets.QLabel(wzpImport)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblGeoCol.sizePolicy().hasHeightForWidth())
        self.lblGeoCol.setSizePolicy(sizePolicy)
        self.lblGeoCol.setObjectName("lblGeoCol")
        self.gridLayout_2.addWidget(self.lblGeoCol, 5, 0, 1, 1)
        self.lblDistrictCol = QtWidgets.QLabel(wzpImport)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDistrictCol.sizePolicy().hasHeightForWidth())
        self.lblDistrictCol.setSizePolicy(sizePolicy)
        self.lblDistrictCol.setObjectName("lblDistrictCol")
        self.gridLayout_2.addWidget(self.lblDistrictCol, 7, 0, 1, 1)
        self.horizontalLayout2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout2.setObjectName("horizontalLayout2")
        self.gbDelimiter = QtWidgets.QGroupBox(wzpImport)
        self.gbDelimiter.setObjectName("gbDelimiter")
        self.gridLayout2 = QtWidgets.QGridLayout(self.gbDelimiter)
        self.gridLayout2.setObjectName("gridLayout2")
        self.rbOther = QtWidgets.QRadioButton(self.gbDelimiter)
        self.rbOther.setObjectName("rbOther")
        self.gridLayout2.addWidget(self.rbOther, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout2.addItem(spacerItem, 3, 2, 1, 1)
        self.rbComma = QtWidgets.QRadioButton(self.gbDelimiter)
        self.rbComma.setChecked(True)
        self.rbComma.setObjectName("rbComma")
        self.gridLayout2.addWidget(self.rbComma, 0, 0, 1, 1)
        self.edOther = QtWidgets.QLineEdit(self.gbDelimiter)
        self.edOther.setEnabled(False)
        self.edOther.setMaxLength(1)
        self.edOther.setObjectName("edOther")
        self.gridLayout2.addWidget(self.edOther, 3, 1, 1, 1)
        self.rbSpace = QtWidgets.QRadioButton(self.gbDelimiter)
        self.rbSpace.setObjectName("rbSpace")
        self.gridLayout2.addWidget(self.rbSpace, 2, 0, 1, 1)
        self.rbTab = QtWidgets.QRadioButton(self.gbDelimiter)
        self.rbTab.setObjectName("rbTab")
        self.gridLayout2.addWidget(self.rbTab, 1, 0, 1, 1)
        self.horizontalLayout2.addWidget(self.gbDelimiter)
        self.gbQuote = QtWidgets.QGroupBox(wzpImport)
        self.gbQuote.setObjectName("gbQuote")
        self.gridLayout = QtWidgets.QGridLayout(self.gbQuote)
        self.gridLayout.setObjectName("gridLayout")
        self.rbSingleQuote = QtWidgets.QRadioButton(self.gbQuote)
        self.rbSingleQuote.setObjectName("rbSingleQuote")
        self.gridLayout.addWidget(self.rbSingleQuote, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 2, 1, 1)
        self.rbDoubleQuote = QtWidgets.QRadioButton(self.gbQuote)
        self.rbDoubleQuote.setChecked(True)
        self.rbDoubleQuote.setObjectName("rbDoubleQuote")
        self.gridLayout.addWidget(self.rbDoubleQuote, 0, 0, 1, 1)
        self.rbOtherQuote = QtWidgets.QRadioButton(self.gbQuote)
        self.rbOtherQuote.setObjectName("rbOtherQuote")
        self.gridLayout.addWidget(self.rbOtherQuote, 2, 0, 1, 1)
        self.edOtherQuote = QtWidgets.QLineEdit(self.gbQuote)
        self.edOtherQuote.setEnabled(False)
        self.edOtherQuote.setMaxLength(1)
        self.edOtherQuote.setObjectName("edOtherQuote")
        self.gridLayout.addWidget(self.edOtherQuote, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 3, 0, 1, 1)
        self.horizontalLayout2.addWidget(self.gbQuote)
        self.gridLayout_2.addLayout(self.horizontalLayout2, 3, 0, 1, 3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 8, 0, 1, 3)
        self.cbxHeaderRow = QtWidgets.QCheckBox(wzpImport)
        self.cbxHeaderRow.setChecked(True)
        self.cbxHeaderRow.setObjectName("cbxHeaderRow")
        self.gridLayout_2.addWidget(self.cbxHeaderRow, 2, 0, 1, 3)
        self.lblImportAssignment = QtWidgets.QLabel(wzpImport)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblImportAssignment.sizePolicy().hasHeightForWidth())
        self.lblImportAssignment.setSizePolicy(sizePolicy)
        self.lblImportAssignment.setObjectName("lblImportAssignment")
        self.gridLayout_2.addWidget(self.lblImportAssignment, 0, 0, 1, 1)
        self.gbPreview = QtWidgets.QGroupBox(wzpImport)
        self.gbPreview.setFlat(True)
        self.gbPreview.setObjectName("gbPreview")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gbPreview)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tbPreview = QtWidgets.QTableWidget(self.gbPreview)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbPreview.sizePolicy().hasHeightForWidth())
        self.tbPreview.setSizePolicy(sizePolicy)
        self.tbPreview.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tbPreview.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tbPreview.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tbPreview.setRowCount(1)
        self.tbPreview.setObjectName("tbPreview")
        self.tbPreview.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tbPreview.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbPreview.setHorizontalHeaderItem(1, item)
        self.tbPreview.horizontalHeader().setMinimumSectionSize(200)
        self.tbPreview.horizontalHeader().setStretchLastSection(True)
        self.tbPreview.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tbPreview)
        self.gridLayout_2.addWidget(self.gbPreview, 4, 0, 1, 3)
        self.lblJoinField = QtWidgets.QLabel(wzpImport)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblJoinField.sizePolicy().hasHeightForWidth())
        self.lblJoinField.setSizePolicy(sizePolicy)
        self.lblJoinField.setObjectName("lblJoinField")
        self.gridLayout_2.addWidget(self.lblJoinField, 1, 0, 1, 1)
        self.cmbJoinField = RdsFieldComboBox(wzpImport)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbJoinField.sizePolicy().hasHeightForWidth())
        self.cmbJoinField.setSizePolicy(sizePolicy)
        self.cmbJoinField.setObjectName("cmbJoinField")
        self.gridLayout_2.addWidget(self.cmbJoinField, 1, 1, 1, 2)
        self.fileImportFrom = RdsFileWidget(wzpImport)
        self.fileImportFrom.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileImportFrom.sizePolicy().hasHeightForWidth())
        self.fileImportFrom.setSizePolicy(sizePolicy)
        self.fileImportFrom.setFilter("*.csv;*.txt;*.xls;*.xlsx;*.ods")
        self.fileImportFrom.setObjectName("fileImportFrom")
        self.gridLayout_2.addWidget(self.fileImportFrom, 0, 1, 1, 2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sbxGeographyCol = QtWidgets.QSpinBox(wzpImport)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbxGeographyCol.sizePolicy().hasHeightForWidth())
        self.sbxGeographyCol.setSizePolicy(sizePolicy)
        self.sbxGeographyCol.setMinimum(1)
        self.sbxGeographyCol.setMaximum(2)
        self.sbxGeographyCol.setObjectName("sbxGeographyCol")
        self.horizontalLayout_2.addWidget(self.sbxGeographyCol)
        self.cmbGeographyCol = QtWidgets.QComboBox(wzpImport)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbGeographyCol.sizePolicy().hasHeightForWidth())
        self.cmbGeographyCol.setSizePolicy(sizePolicy)
        self.cmbGeographyCol.setObjectName("cmbGeographyCol")
        self.horizontalLayout_2.addWidget(self.cmbGeographyCol)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 5, 1, 1, 2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.sbxDistrictCol = QtWidgets.QSpinBox(wzpImport)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbxDistrictCol.sizePolicy().hasHeightForWidth())
        self.sbxDistrictCol.setSizePolicy(sizePolicy)
        self.sbxDistrictCol.setMinimum(1)
        self.sbxDistrictCol.setMaximum(2)
        self.sbxDistrictCol.setProperty("value", 2)
        self.sbxDistrictCol.setObjectName("sbxDistrictCol")
        self.horizontalLayout_3.addWidget(self.sbxDistrictCol)
        self.cmbDistrictCol = QtWidgets.QComboBox(wzpImport)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbDistrictCol.sizePolicy().hasHeightForWidth())
        self.cmbDistrictCol.setSizePolicy(sizePolicy)
        self.cmbDistrictCol.setObjectName("cmbDistrictCol")
        self.horizontalLayout_3.addWidget(self.cmbDistrictCol)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 7, 1, 1, 2)
        self.lblGeoCol.setBuddy(self.sbxGeographyCol)
        self.lblDistrictCol.setBuddy(self.sbxDistrictCol)
        self.lblImportAssignment.setBuddy(self.fileImportFrom)
        self.lblJoinField.setBuddy(self.cmbJoinField)

        self.retranslateUi(wzpImport)
        self.rbOther.toggled['bool'].connect(self.edOther.setEnabled)
        self.rbOther.toggled['bool'].connect(self.edOther.setFocus)
        QtCore.QMetaObject.connectSlotsByName(wzpImport)
        wzpImport.setTabOrder(self.cbxHeaderRow, self.rbComma)
        wzpImport.setTabOrder(self.rbComma, self.rbTab)
        wzpImport.setTabOrder(self.rbTab, self.rbSpace)
        wzpImport.setTabOrder(self.rbSpace, self.rbOther)
        wzpImport.setTabOrder(self.rbOther, self.edOther)
        wzpImport.setTabOrder(self.edOther, self.rbDoubleQuote)
        wzpImport.setTabOrder(self.rbDoubleQuote, self.rbSingleQuote)
        wzpImport.setTabOrder(self.rbSingleQuote, self.rbOtherQuote)
        wzpImport.setTabOrder(self.rbOtherQuote, self.edOtherQuote)
        wzpImport.setTabOrder(self.edOtherQuote, self.sbxGeographyCol)
        wzpImport.setTabOrder(self.sbxGeographyCol, self.cmbGeographyCol)
        wzpImport.setTabOrder(self.cmbGeographyCol, self.sbxDistrictCol)
        wzpImport.setTabOrder(self.sbxDistrictCol, self.cmbDistrictCol)

    def retranslateUi(self, wzpImport):
        _translate = QtCore.QCoreApplication.translate
        wzpImport.setWindowTitle(_translate("wzpImport", "Import Assignments"))
        wzpImport.setTitle(_translate("wzpImport", "Import Assignments"))
        wzpImport.setSubTitle(_translate("wzpImport", "Import district assignments from a geogrpahic equivalency file"))
        self.lblGeoCol.setText(_translate("wzpImport", "&Geography Column"))
        self.lblDistrictCol.setText(_translate("wzpImport", "&District Column"))
        self.gbDelimiter.setToolTip(_translate("wzpImport", "Select or enter the field delimiter"))
        self.gbDelimiter.setTitle(_translate("wzpImport", "Delimiter"))
        self.rbOther.setText(_translate("wzpImport", "&Other character"))
        self.rbComma.setText(_translate("wzpImport", "&Comma"))
        self.rbSpace.setText(_translate("wzpImport", "&Space"))
        self.rbTab.setText(_translate("wzpImport", "&Tab"))
        self.gbQuote.setToolTip(_translate("wzpImport", "Select or enter the quote character that will define field values"))
        self.gbQuote.setTitle(_translate("wzpImport", "Text Qualifier"))
        self.rbSingleQuote.setText(_translate("wzpImport", "Single Quote"))
        self.rbDoubleQuote.setText(_translate("wzpImport", "Double Quote"))
        self.rbOtherQuote.setText(_translate("wzpImport", "Other character"))
        self.cbxHeaderRow.setToolTip(_translate("wzpImport", "Check if the equivalency file includes a header row"))
        self.cbxHeaderRow.setText(_translate("wzpImport", "File has &header row"))
        self.lblImportAssignment.setText(_translate("wzpImport", "&Import From"))
        self.gbPreview.setTitle(_translate("wzpImport", "Preview"))
        item = self.tbPreview.horizontalHeaderItem(0)
        item.setText(_translate("wzpImport", "Geography ID"))
        item = self.tbPreview.horizontalHeaderItem(1)
        item.setText(_translate("wzpImport", "District"))
        self.lblJoinField.setToolTip(_translate("wzpImport", "Geography field on which equivalency file will be joined to assignments layer", "redistricting"))
        self.lblJoinField.setText(_translate("wzpImport", "Assigment Geography"))
        self.cmbJoinField.setToolTip(_translate("wzpImport", "Choose the geography field on which equivalency file will be joined to assignments layer"))
        self.fileImportFrom.setToolTip(_translate("wzpImport", "Select the equivalency file from which assignments will be imported"))
        self.fileImportFrom.setStatusTip(_translate("wzpImport", "Choose an equivalency file to import"))
        self.fileImportFrom.setDialogTitle(_translate("wzpImport", "Select Equivalency File"))
        self.sbxGeographyCol.setToolTip(_translate("wzpImport", "Choose the column that will be matched to the geography in the assignment layer"))
        self.cmbGeographyCol.setToolTip(_translate("wzpImport", "Choose the column that will be matched to the geography in the assignment layer"))
        self.sbxDistrictCol.setToolTip(_translate("wzpImport", "Choose the column that will be imported as the district for the corresponding unit of geography"))
        self.cmbDistrictCol.setToolTip(_translate("wzpImport", "Choose the column that will be imported as the district for the corresponding unit of geography"))
from .RedistrictingWidgets import RdsFieldComboBox, RdsFileWidget
